### ISSUE TITLE
2-way bindings deprecated

### ISSUE THREAD

**Issue by jollyMZ** [JochenHeckl/DataBinding#2]
I saw that the 2-way bindings are in the deprecated folder without any replacement. I definitely like the newer format as it is much simpler to the user. I was curious as to what the plan for 2-way bindings was and if you found a way to generalize the change events that come from Input UI.

**Comment by JochenHeckl** [comment]
Thanks for your feedback @jollyMZ,
 
well the thing about 2 way bindings is that they do not play too well with the whole declarative idea.
So in imho the preferred way to deal with feedback from the UI is to simply bind actions that in turn do manipulate your DataSource.

If you import the simple examples included in version 1.3.1 and open up the two way binding scene you will find two dropdowns populated with both 2 way bindings and a bound action approach.

I personally prefer the way of binding an action - especially because I think the overall principle is simpler to understand this way. Just bind an action like you would otherwise bind a value.
